services:
  mangashelf:
    build: .
    image: mangashelf
    container_name: mangashelf
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - mangashelf-data:/code/data
    env_file:
      - .env

volumes:
  mangashelf-data:
